import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const source=readFileSync(new URL('../dist/app.js',import.meta.url),'utf8');
const boundary="document.querySelectorAll('[data-mode]').forEach(b=>b.onclick";
const context=vm.createContext({document:{getElementById:()=>({value:'test'})}});
vm.runInContext(source.slice(0,source.indexOf(boundary)),context);
const run=code=>vm.runInContext(code,context);
context.fixture=JSON.parse(readFileSync(new URL('context.geojson',import.meta.url),'utf8'));
context.invalid=JSON.parse(readFileSync(new URL('invalid.geojson',import.meta.url),'utf8'));
assert.equal(run('parseGeoJSON(fixture).features.length'),5);
assert.equal(run('parseGeoJSON(fixture).features.find(f=>f.layer==="buildings").height'),35);
assert.equal(run('parseGeoJSON(fixture).features.find(f=>f.layer==="buildings").holes.length'),1);
assert.equal(run('parseGeoJSON(fixture).geographic'),true);
assert.throws(()=>run('parseGeoJSON(invalid)'),/座標/);
assert.throws(()=>run('parseGeoJSON({type:"FeatureCollection",features:[]})'),/要素数/);
const roundtrip=run('JSON.stringify(restoreProject(JSON.parse(JSON.stringify({format:"strata-project",version:1,state}))))');
assert.deepEqual(JSON.parse(roundtrip),JSON.parse(run('JSON.stringify(state)')));
assert.throws(()=>run('restoreProject({format:"strata-project",version:1,state:{...state,layers:[]}})'),/レイヤー/);
assert.throws(()=>run('restoreProject({format:"strata-project",version:1,state:{...state,extent:0}})'),/表示設定/);
assert.equal(run('sampleFeatures().every(f=>f.ring.every(p=>p.every(Number.isFinite)))'),true);
console.log('PASS: GeoJSON import, holes, heights, invalid input, project round-trip, invalid project, sample coordinates (10 checks)');
